### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Michael21107**
updated the RPH link to direct to the discord server, since the latest RPH version isn't on the website)

### CODE REVIEW

**Comment by Variapolis** [comment]
The link has been reverted to the discord which has the latest version, the rest has been squashed and merged from #19. I won't be specifying installation instructions for RagePluginHook as that can change and is dependent on RagePluginHook's maintainers.

**Comment by AgentBlackout** [comment]
Fed.

**Comment by Michael21107** [comment]
not sure what you wanted to do but now its linked to the website which doesn't have the latest RPH version

**Comment by Variapolis** [comment]
Hadn't pushed the change yet. Fixed now.

**Pull request closed without merging**
